<?php
$objectManager =\Magento\Framework\App\ObjectManager::getInstance();
$helper = $objectManager->get('Redeal\Referralmarketing\Helper\Data');
//$write = $helper->getConfigValue('redeal_general/general/custommode');
$isactive = $helper->getConfigValue('redeal_general/general/active');
//echo $isactive;
//$write = $helper->getConfigValue('redeal_general/general/custommode');


$redlurl = "//widget.redeal.se/js/redeal.js";
/*if($write == 2)
{
$redlurl = "//widget.redeal.se/js/redeal.js";
 }
else
{
 $redlurl = "//test-widget.redeal.se/js/redeal.js";
}*/
?>
<?php if($isactive == 1) { ?>
<script>
	(function(i,s,o,g,r,a,m){i['RedealObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window, document, 'script', window.location.protocol + '<?php echo $redlurl;?>', 'redeal');
</script>
<script>
    var require = {
        "baseUrl": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('/') ?>"
    };
</script>

<?php } ?>