<?php /** @var $block \Redeal\Referralmarketing\Block\Success */ ?>
<div class="checkout-success">

    <?php 
    if ($block->getOrderId()):

    $objectManager =\Magento\Framework\App\ObjectManager::getInstance();
    $orderdetail = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId($block->getOrderId());
    $productdetail = $block->getItems();
    $store = $objectManager->get('Magento\Framework\Locale\Resolver'); 

    $customerdetail = $block->getCustomerOrderDetail();
    foreach ($customerdetail as $address)
    {
        $firstname = $address['firstname'];
        $phone = $address['telephone'];
        $country = $objectManager->create('\Magento\Directory\Model\Country')->load($address['country_id'])->getName();
    }
       

     
       
        ?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php else: ?>
            <p><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif; ?>

        

        <p><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif; ?>

    <?php echo $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>

 

<script>
     
    redeal('checkout', 
    {
        id: "<?php echo $orderdetail->getIncrementId(); ?>",
        name: "<?php echo $firstname; ?>",
        total: "<?php echo number_format($orderdetail->getGrandTotal(), 2, '.', ''); ?>",
        price: "<?php echo number_format($orderdetail->getSubtotal(), 2, '.', ''); ?>",
        tax: "<?php echo number_format($orderdetail->getTaxAmount(), 2, '.', ''); ?>",
        shipping: "<?php echo number_format($orderdetail->getShippingAmount(), 2, '.', ''); ?>",
        currency: "<?php echo $orderdetail->getOrderCurrencyCode(); ?>",
        country: "<?php echo $country; ?>",
        language: "<?php echo substr($store->getLocale(), 0, strpos($store->getLocale(), "_")); ?>",
        email: "<?php echo $orderdetail->getCustomerEmail(); ?>",
        phone: "<?php echo $phone; ?>", 
        coupons: [ "<?php echo $orderdetail->getCouponCode(); ?>" ],
        products: <?php echo $productdetail; ?>
    });


    window.dataLayer = window.dataLayer || [];
    window.dataLayer.push({
      'ecommerce': {
        'purchase': {
          'actionField': {
            'id': '<?php echo $orderdetail->getIncrementId()?>', 
            'revenue': '<?php echo number_format($orderdetail->getGrandTotal(), 2, '.', ''); ?>',
            'tax': '<?php echo number_format($orderdetail->getTaxAmount(), 2, '.', ''); ?>',
            'shipping': '<?php echo number_format($orderdetail->getShippingAmount(), 2, '.', ''); ?>',
            'currency': '<?php echo $orderdetail->getOrderCurrencyCode(); ?>',
            'coupon': '<?php echo $orderdetail->getCouponCode(); ?>',
            'products': '<?php echo $productdetail; ?>'
          },
          
         
        }
      }
    });
  
</script>
<script type="text/javascript">
    require([
    "jquery",
    'mage/template',
    "mage/mage"
], function (){
    console.log("REDEAL REFERRALMARKETING");
    console.log("id: <?php echo $orderdetail->getIncrementId(); ?>,");
    console.log("name: <?php echo $firstname; ?>,");
    console.log("total: <?php echo number_format($orderdetail->getGrandTotal(), 2, '.', ''); ?>,");
    console.log("price: <?php echo number_format($orderdetail->getSubtotal(), 2, '.', ''); ?>,");
    console.log("tax: <?php echo number_format($orderdetail->getTaxAmount(), 2, '.', ''); ?>,");
    console.log("shipping: <?php echo number_format($orderdetail->getShippingAmount(), 2, '.', ''); ?>,");
    console.log("currency: <?php echo $orderdetail->getOrderCurrencyCode(); ?>,");
    console.log("country: <?php echo $country; ?>,");
    console.log("language: <?php echo substr($store->getLocale(), 0, strpos($store->getLocale(), "_")); ?>,");
    console.log("email: <?php echo $orderdetail->getCustomerEmail(); ?>,");
    console.log("phone: <?php echo $phone; ?>, ");
    console.log("coupons: [ <?php echo $orderdetail->getCouponCode(); ?> ],");
    console.log('products: <?php echo $productdetail; ?>');

    console.log(" ");
    
    console.log("Google Tag Manager");
    console.log("id: <?php echo $orderdetail->getIncrementId(); ?>,");
    console.log("revenue: <?php echo number_format($orderdetail->getGrandTotal(), 2, '.', ''); ?>,");
    console.log("tax: <?php echo number_format($orderdetail->getTaxAmount(), 2, '.', ''); ?>,");
    console.log("shipping: <?php echo number_format($orderdetail->getShippingAmount(), 2, '.', ''); ?>,");
    console.log("currency: <?php echo $orderdetail->getOrderCurrencyCode(); ?>,");
    console.log("coupon: <?php echo $orderdetail->getCouponCode(); ?>,");
    console.log('products: <?php echo $productdetail; ?>');
});
</script>